version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    build:  # checking if this behaves as I expect...
      python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: docs/requirements.txt
    # actually install this python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  #fail_on_warning: true
